### PR TITLE
Add missing word: Caltor

### PR DESCRIPTION
**Pull request by stivaugoin**

### CODE REVIEW

**Review by henrymyers — CHANGES_REQUESTED** [review]
Never heard that one, but I see now that it's pretty well known!

I would suggest adding it to the "Câlisse" family array though.

**Comment by henrymyers** [comment]
See:

https://www.google.com/books/edition/Speak_Qu%C3%A9bec/obzpDAAAQBAJ?hl=en&gbpv=1&dq=juron+%22caltor%22&pg=PT25&printsec=frontcover

**Comment by stivaugoin** [comment]
@henrymyers Good idea. I made the change.

**Comment by ctaschereau** [comment]
@stivaugoin thanks for your great contribution to this project :) I look forward to using this new feature in my next projects ;)

**Review by henrymyers — APPROVED** [review]
Merci!

**Pull request merged**
