### PR TITLE
Python implementation

### PR DESCRIPTION
**Pull request by RosaliePerron**

### CODE REVIEW

**Comment by henrymyers** [comment]
I could be wrong, but shouldn't the Python version be in a standalone repo? I'd happily add a link to it in the readme!

**Comment by henrymyers** [comment]
I could also export the swears, which would allow you to directly import them in your repo via `https://pypi.org/project/pynpm/`

**Comment by henrymyers** [comment]
Love the idea, though! I know @bishiboosh is working on a Kotlin port too!

**Comment by RosaliePerron** [comment]
> I could be wrong, but shouldn't the Python version be in a standalone repo? I'd happily add a link to it in the readme!

I'm gonna do that !

**Comment by henrymyers** [comment]
Perfect! I'll close this PR then, and let me know here when you're done 😄

**Pull request closed without merging**
